### ISSUE TITLE
404 for documentation

### ISSUE THREAD

**Issue by mcarton** [unicode-rs/unicode-security#14]
The [documentation link](https://github.com/unicode-rs/unicode-security/blob/4c51184fd8f9c42a7b2fd8c2c4393d36f9f69231/Cargo.toml#L8) gives a 404: https://unicode-rs.github.io/unicode-security

**Comment by Manishearth** [comment]
We should just use docs.rs

**Comment by crlf0710** [comment]
Resolved in #19.
